# Generated by Django 6.1.1 on 2026-09-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
                ('resumen', models.TextField(verbose_name='Resumen')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='noticias.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha', 'titulo'],
            },
        ),
    ]
