# Generated by Django 6.1.1 on 2026-09-27 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('director', models.CharField(max_length=150, verbose_name='Director')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Calificación')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('estreno', models.BooleanField(default=False, verbose_name='Estreno')),
                ('imagen', models.CharField(blank=True, max_length=200, verbose_name='Imagen')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peliculas', to='cine.genero', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-anio', 'titulo'],
            },
        ),
    ]
